import type { MarketingWeek } from "./types";

const IMG = "/landing/month-plan";

/**
 * Illustrative August demo month — not real customer data or a persisted
 * plan. Four strategic weeks, five daily ideas each. Each daily idea is one
 * core concept; its `executions` are the platform-specific versions made
 * from that idea (1–3 per idea, never all five channels on one card). Every
 * idea has its own unique photo — no week reuses one image across its daily
 * cards.
 */
export const augustMonthPlan: MarketingWeek[] = [
  {
    id: "week-1",
    label: "Week 1",
    dateRange: "August 1 – August 7",
    theme: "Pour-Over Coffee Rituals",
    description:
      "Explore the art of slowing down. This week, we're sharing simple rituals, expert tips, and mindful moments that turn your daily brew into something extraordinary.",
    strategyTitle: "Strategy: Educate & Inspire",
    strategyDescription:
      "Teach the why and how behind better coffee. Build trust through value-driven content.",
    heroImageSrc: `${IMG}/week1-pour-over.png`,
    heroImageAlt: "Pour-over coffee ritual with dripper, kettle, and mug",
    totalCount: 5,
    posts: [
      {
        id: "week-1-mon",
        day: "Monday",
        date: "Aug 1",
        title: "The Perfect Pour-Over Start",
        description: "A beginner-friendly guide to your first great pour.",
        imageSrc: `${IMG}/monday-pour-over-start.png`,
        imageAlt: "Full pour-over coffee setup on a wooden counter",
        contentType: "educational",
        executions: [
          { channel: "facebook", format: "carousel" },
          { channel: "instagram", format: "carousel" },
        ],
        status: "planned",
      },
      {
        id: "week-1-tue",
        day: "Tuesday",
        date: "Aug 2",
        title: "Pour-Over in 30 Seconds",
        description: "The whole ritual, condensed into one fast clip.",
        imageSrc: `${IMG}/wednesday-pour-over-short.png`,
        imageAlt: "Quick pour-over coffee scene styled for a short-form video",
        contentType: "quick-tip",
        executions: [
          { channel: "youtube", format: "short" },
          { channel: "tiktok", format: "short" },
        ],
        status: "planned",
      },
      {
        id: "week-1-wed",
        day: "Wednesday",
        date: "Aug 3",
        title: "Why Grind Size Changes Everything",
        description: "Coarse vs. fine — how grind size reshapes the cup.",
        imageSrc: `${IMG}/week1-grind-size.png`,
        imageAlt: "Two piles of coffee grounds, coarse and fine, side by side",
        contentType: "educational",
        executions: [
          { channel: "linkedin", format: "post" },
          { channel: "facebook", format: "post" },
        ],
        status: "planned",
      },
      {
        id: "week-1-thu",
        day: "Thursday",
        date: "Aug 4",
        title: "Essential Pour-Over Tools",
        description: "The short list of gear worth actually owning.",
        imageSrc: `${IMG}/thursday-coffee-tools.png`,
        imageAlt: "Pour-over coffee tools including kettle, grinder, and scale",
        contentType: "product-spotlight",
        executions: [
          { channel: "instagram", format: "carousel" },
          { channel: "linkedin", format: "post" },
        ],
        status: "scheduled",
      },
      {
        id: "week-1-fri",
        day: "Friday",
        date: "Aug 5",
        title: "My Morning Coffee Ritual",
        description: "A personal, unhurried look at how the week began.",
        imageSrc: `${IMG}/friday-coffee-inspiration.png`,
        imageAlt: "Hand holding a handmade coffee mug near a café table",
        contentType: "lifestyle",
        executions: [
          { channel: "youtube", format: "video" },
          { channel: "instagram", format: "reel" },
          { channel: "tiktok", format: "short" },
        ],
        status: "draft",
      },
    ],
  },
  {
    id: "week-2",
    label: "Week 2",
    dateRange: "August 8 – August 14",
    theme: "Beans, Blends & Origins",
    description:
      "Go behind the roast. This week traces where our coffee comes from, how blends are built, and what makes single-origin beans worth talking about.",
    strategyTitle: "Strategy: Build Trust & Craft",
    strategyDescription:
      "Show the sourcing and craft behind every cup. Give regulars a reason to care where their coffee comes from.",
    heroImageSrc: `${IMG}/week2-beans-origins.png`,
    heroImageAlt: "Roasted specialty coffee beans with a metal scoop",
    totalCount: 5,
    posts: [
      {
        id: "week-2-mon",
        day: "Monday",
        date: "Aug 8",
        title: "The Journey of a Coffee Bean",
        description: "From cherry to cup, in one visual story.",
        imageSrc: `${IMG}/week2-bean-journey.png`,
        imageAlt: "Coffee beans shown at three roast stages, green to dark",
        contentType: "educational",
        executions: [
          { channel: "facebook", format: "post" },
          { channel: "instagram", format: "carousel" },
        ],
        status: "planned",
      },
      {
        id: "week-2-tue",
        day: "Tuesday",
        date: "Aug 9",
        title: "Single-Origin vs. Blends, Explained",
        description: "A side-by-side taste of two very different beans.",
        imageSrc: `${IMG}/week2-single-origin-compare.png`,
        imageAlt: "Two bowls of coffee beans, light roast and dark roast, side by side",
        contentType: "how-to",
        executions: [
          { channel: "youtube", format: "video" },
          { channel: "linkedin", format: "post" },
        ],
        status: "planned",
      },
      {
        id: "week-2-wed",
        day: "Wednesday",
        date: "Aug 10",
        title: "Behind the Roast: Our Process",
        description: "Inside the drum roaster where flavor actually happens.",
        imageSrc: `${IMG}/week2-roasting-process.png`,
        imageAlt: "Small-batch coffee roasting drum machine with beans visible",
        contentType: "lifestyle",
        executions: [
          { channel: "instagram", format: "reel" },
          { channel: "tiktok", format: "short" },
        ],
        status: "scheduled",
      },
      {
        id: "week-2-thu",
        day: "Thursday",
        date: "Aug 11",
        title: "Tasting Notes 101",
        description: "How professional cuppers actually taste a coffee.",
        imageSrc: `${IMG}/week2-cupping-tasting.png`,
        imageAlt: "Coffee cupping setup with bowls of brewed coffee and spoons",
        contentType: "quick-tip",
        executions: [
          { channel: "tiktok", format: "video" },
          { channel: "youtube", format: "short" },
        ],
        status: "draft",
      },
      {
        id: "week-2-fri",
        day: "Friday",
        date: "Aug 12",
        title: "Seasonal Menu Sneak Peek",
        description: "Two new seasonal drinks, before they hit the counter.",
        imageSrc: `${IMG}/week2-seasonal-menu.png`,
        imageAlt: "Iced and hot seasonal coffee drinks on a café counter",
        contentType: "product-spotlight",
        executions: [
          { channel: "facebook", format: "carousel" },
          { channel: "instagram", format: "carousel" },
          { channel: "linkedin", format: "post" },
        ],
        status: "draft",
      },
    ],
  },
  {
    id: "week-3",
    label: "Week 3",
    dateRange: "August 15 – August 21",
    theme: "Latte Art at Home",
    description:
      "Bring café-quality moments home. This week is about steaming milk with confidence and making every cup feel a little more special.",
    strategyTitle: "Strategy: Delight & Engage",
    strategyDescription:
      "Turn a technical skill into something fun and shareable. Encourage regulars to try it themselves.",
    heroImageSrc: `${IMG}/week3-latte-art.png`,
    heroImageAlt: "Latte with leaf-pattern latte art on a café table",
    totalCount: 5,
    posts: [
      {
        id: "week-3-mon",
        day: "Monday",
        date: "Aug 15",
        title: "Brew Guide: Café-Quality at Home",
        description: "The full walkthrough for a better cup at your counter.",
        imageSrc: `${IMG}/week3-brew-guide.png`,
        imageAlt: "Home pour-over brewing setup with dripper, kettle, and scale",
        contentType: "how-to",
        executions: [
          { channel: "youtube", format: "video" },
          { channel: "facebook", format: "post" },
        ],
        status: "planned",
      },
      {
        id: "week-3-tue",
        day: "Tuesday",
        date: "Aug 16",
        title: "Milk Steaming Basics",
        description: "The one technique that makes latte art possible.",
        imageSrc: `${IMG}/week3-milk-steaming.png`,
        imageAlt: "Steaming pitcher pouring silky milk into a ceramic cup",
        contentType: "quick-tip",
        executions: [
          { channel: "tiktok", format: "short" },
          { channel: "instagram", format: "reel" },
        ],
        status: "draft",
      },
      {
        id: "week-3-wed",
        day: "Wednesday",
        date: "Aug 17",
        title: "Meet Our Roaster: A Trust Story",
        description: "A quiet look inside the space where it all starts.",
        imageSrc: `${IMG}/week3-roastery-portrait.png`,
        imageAlt: "Artisanal roastery workspace with burlap sacks and equipment",
        contentType: "lifestyle",
        executions: [
          { channel: "instagram", format: "carousel" },
          { channel: "linkedin", format: "post" },
        ],
        status: "draft",
      },
      {
        id: "week-3-thu",
        day: "Thursday",
        date: "Aug 18",
        title: "Latte Art Tools Spotlight",
        description: "The small kit that makes home latte art achievable.",
        imageSrc: `${IMG}/week3-latte-tools.png`,
        imageAlt: "Latte art milk pitcher and espresso tools on a counter",
        contentType: "product-spotlight",
        executions: [
          { channel: "instagram", format: "carousel" },
          { channel: "facebook", format: "post" },
        ],
        status: "draft",
      },
      {
        id: "week-3-fri",
        day: "Friday",
        date: "Aug 19",
        title: "Coffee vs. Matcha: Quick Take",
        description: "Two favorite rituals, side by side, no winner declared.",
        imageSrc: `${IMG}/week3-coffee-vs-matcha.png`,
        imageAlt: "A cup of coffee and a bowl of matcha side by side",
        contentType: "quick-tip",
        executions: [
          { channel: "tiktok", format: "short" },
          { channel: "instagram", format: "reel" },
          { channel: "youtube", format: "short" },
        ],
        status: "draft",
      },
    ],
  },
  {
    id: "week-4",
    label: "Week 4",
    dateRange: "August 22 – August 31",
    theme: "Café Stories & Local Love",
    description:
      "Close out the month by celebrating the community. Regulars, local stories, and a look ahead to what's brewing next month.",
    strategyTitle: "Strategy: Community & Reflection",
    strategyDescription:
      "Recap the month's wins and spotlight the people who make the café feel like home.",
    heroImageSrc: `${IMG}/week4-cafe-stories.png`,
    heroImageAlt: "Warm independent café interior with plants and wood tables",
    totalCount: 5,
    posts: [
      {
        id: "week-4-mon",
        day: "Monday",
        date: "Aug 22",
        title: "This Month in Review",
        description: "The month's highlights, wrapped up in one recap.",
        imageSrc: `${IMG}/week4-monthly-recap.png`,
        imageAlt: "Flat lay of a blank notepad surrounded by coffee beans and a cup",
        contentType: "educational",
        executions: [
          { channel: "facebook", format: "post" },
          { channel: "instagram", format: "carousel" },
        ],
        status: "draft",
      },
      {
        id: "week-4-tue",
        day: "Tuesday",
        date: "Aug 23",
        title: "Regulars Spotlight: Community Favorites",
        description: "The table that turns strangers into regulars.",
        imageSrc: `${IMG}/week4-community-table.png`,
        imageAlt: "Communal café table set with mismatched cups and pastries",
        contentType: "lifestyle",
        executions: [
          { channel: "instagram", format: "carousel" },
          { channel: "facebook", format: "post" },
          { channel: "linkedin", format: "post" },
        ],
        status: "draft",
      },
      {
        id: "week-4-wed",
        day: "Wednesday",
        date: "Aug 24",
        title: "Café Stories: Why We Roast Local",
        description: "The sourcing decision behind every local bag sold.",
        imageSrc: `${IMG}/week4-local-roasting.png`,
        imageAlt: "Raw green coffee beans in a wooden crate with a sample roaster",
        contentType: "educational",
        executions: [
          { channel: "youtube", format: "video" },
          { channel: "linkedin", format: "post" },
        ],
        status: "empty",
      },
      {
        id: "week-4-thu",
        day: "Thursday",
        date: "Aug 25",
        title: "Your Coffee, Your Ritual",
        description: "Slowing down for one cup, wherever the day happens.",
        imageSrc: `${IMG}/week4-personal-ritual.png`,
        imageAlt: "Coffee mug beside an open book and blanket on a windowsill",
        contentType: "quick-tip",
        executions: [
          { channel: "tiktok", format: "short" },
          { channel: "instagram", format: "reel" },
        ],
        status: "empty",
      },
      {
        id: "week-4-fri",
        day: "Friday",
        date: "Aug 26",
        title: "Sneak Peek: Next Month's Theme",
        description: "A first look at what's brewing for next month.",
        imageSrc: `${IMG}/week4-next-month-teaser.png`,
        imageAlt: "Cold brew coffee with ice and mint on a sunlit outdoor table",
        contentType: "product-spotlight",
        executions: [
          { channel: "facebook", format: "post" },
          { channel: "instagram", format: "carousel" },
          { channel: "tiktok", format: "short" },
        ],
        status: "empty",
      },
    ],
  },
];
